# Generated by Django 4.2.2 on 2023-06-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
